# Generated by Django 5.2 on 2025-08-29 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only letters and spaces are allowed.')], verbose_name='username')),
                ('email', models.EmailField(default='example@gmail.com', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
