# Generated by Django 5.2 on 2025-09-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0002_coursemodel_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='current_sem',
            field=models.IntegerField(default=1),
        ),
    ]
