# Generated by Django 5.2 on 2025-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_rename_course_name_coursemodel_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='enroll_id',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
