# Generated by Django 5.2 on 2025-08-30 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('course_code', models.CharField(max_length=5, unique=True)),
                ('total_sem', models.IntegerField(default=8)),
            ],
            options={
                'db_table': 'CourseTable',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(validators=[django.core.validators.RegexValidator(message='Username must start with a letter and contain only letters, numbers, dots, or underscores. Min 3 characters.', regex='^[a-zA-Z][a-zA-Z0-9._]{2,29}$')])),
                ('email', models.EmailField(default='example@gmail.com', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$')])),
                ('usr_password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters, include uppercase, lowercase, number, and special character.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')])),
                ('roles', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UserTable',
            },
        ),
    ]
