# Generated by Django 5.2 on 2025-09-24 10:08

import django.core.validators
import django.db.models.deletion
import student_management_system.auth.resetpassword.model.password_reset_model
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('course_code', models.CharField(max_length=5, unique=True)),
                ('total_sem', models.IntegerField(default=8)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='Courses/')),
            ],
            options={
                'db_table': 'CourseTable',
            },
        ),
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('l_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('emp_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
            ],
            options={
                'db_table': 'TeachersTable',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('HR', 'HR'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTANT', 'Accountant'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('TRANSPORT_MANAGER', 'Transport Manager')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'UserTable',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=student_management_system.auth.resetpassword.model.password_reset_model.get_expiry_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterModel',
            fields=[
                ('sem_id', models.CharField(primary_key=True, serialize=False)),
                ('sem_name', models.CharField(max_length=25)),
                ('sem_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_system.coursemodel')),
            ],
            options={
                'db_table': 'SemesterModel',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('l_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('enroll_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('current_sem', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_management_system.coursemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StudentTable',
            },
        ),
        migrations.CreateModel(
            name='SubjectsModel',
            fields=[
                ('sub_id', models.CharField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('sub_code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('sub_credit', models.PositiveSmallIntegerField()),
                ('sub_descriptions', models.TextField(blank=True, max_length=200, null=True)),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('lab', 'Lab'), ('project', 'Project')], default='core', max_length=10)),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_system.semestermodel')),
            ],
            options={
                'db_table': 'SubjectsModel',
            },
        ),
    ]
