# Generated by Django 5.2 on 2025-09-02 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('course_code', models.CharField(max_length=5, unique=True)),
                ('total_sem', models.IntegerField(default=8)),
            ],
            options={
                'db_table': 'CourseTable',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('l_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('enroll_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_management_system.coursemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StudentTable',
            },
        ),
    ]
