# Generated by Django 5.2 on 2025-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestermodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestermodel',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
