# Generated by Django 5.2 on 2025-08-31 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('l_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('emp_id', models.CharField(editable=False, max_length=10, unique=True)),
            ],
            options={
                'db_table': 'TeacherTable',
            },
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='usr_password',
            field=models.CharField(max_length=130, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters, include uppercase, lowercase, number, and special character.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$')]),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('l_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces, 2-50 characters.', regex='^[A-Za-z ]{2,50}$')])),
                ('enroll_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student_management_system.coursemodel')),
            ],
        ),
    ]
