# Generated by Django 5.2 on 2025-09-27 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0002_alter_semestermodel_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentModel',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped')], default='active', max_length=10)),
                ('promoted_at', models.DateField(auto_now=True)),
                ('grade', models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='student_management_system.semestermodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student_management_system.studentmodel')),
            ],
        ),
    ]
