# Generated by Django 5.2 on 2025-08-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0002_teachermodel_alter_usermodel_usr_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentmodel',
            table='StudentTable',
        ),
    ]
