# Generated by Django 5.2 on 2025-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_studentmodel_current_sem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='Course_name',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='Courses/'),
        ),
    ]
