# Generated by Django 5.2 on 2025-08-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_alter_studentmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='usr_password',
            new_name='password',
        ),
    ]
