# Generated by Django 5.2 on 2025-09-27 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_studentenrollmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('cs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cs_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('section', models.CharField(max_length=2)),
                ('year', models.PositiveBigIntegerField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('is_activated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_system.coursemodel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_system.semestermodel')),
            ],
        ),
    ]
