# Generated by Django 5.2 on 2025-09-27 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_classmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassModel',
            fields=[
                ('sc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('backlog', 'Backlog'), ('repeated', 'Repeated')], default='active', max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_system.classmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_system.studentmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'class_obj'), name='unique_student_class_sem')],
            },
        ),
    ]
